#!/usr/bin/env python3
"""Deterministic invented substitution cipher — V2.1 TRUE negative control.

rot13 failed as a negative control (models decode it from prior). This
module builds a SEEDED, INVENTED letter/digit substitution table with no
prior exposure: same seed -> same table, always. The shipped table file
(codebook/cipher_v21.json) documents the mapping so the control is
auditable; it is deliberately NOT part of the published-codebook tables
loaded by tcb.tables (provenance marks it as invented).
"""

import argparse
import json
import os
import string
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
TABLE_PATH = os.path.join(_ROOT, "codebook", "cipher_v21.json")
DEFAULT_SEED = 20260930
PROVENANCE = (
    "INVENTED seeded substitution cipher for the V2.1 negative-control arm "
    "(replaces rot13, which models decode from prior). NOT a published code; "
    "no model has prior exposure by construction. Generated by ab/cipher.py "
    "build_table(seed) — deterministic: same seed always yields this table."
)


def _derangement(rng, alphabet):
    """Deterministic permutation of `alphabet` with no fixed points."""
    while True:
        perm = list(alphabet)
        rng.shuffle(perm)
        if all(a != b for a, b in zip(alphabet, perm)):
            return dict(zip(alphabet, perm))


def build_table(seed=DEFAULT_SEED):
    """Seeded table: derangement over a-z and over 0-9 (case preserved on
    encode; non-alphanumeric characters pass through untouched)."""
    rng = _rng_from_seed(seed)
    return {
        "provenance": PROVENANCE,
        "seed": seed,
        "letters": _derangement(rng, string.ascii_lowercase),
        "digits": _derangement(rng, string.digits),
    }


def _rng_from_seed(seed):
    import random

    return random.Random(f"tcb-v21-cipher:{seed}")


def validate_table(table):
    if not isinstance(table, dict):
        raise ValueError("cipher table is not an object")
    for field in ("provenance", "seed", "letters", "digits"):
        if field not in table:
            raise ValueError(f"cipher table missing field {field!r}")
    if "INVENTED" not in table["provenance"]:
        raise ValueError("cipher table provenance must mark it as invented")
    letters, digits = table["letters"], table["digits"]
    if sorted(letters) != list(string.ascii_lowercase):
        raise ValueError("cipher letters must map exactly a-z")
    if sorted(digits) != list(string.digits):
        raise ValueError("cipher digits must map exactly 0-9")
    for mapping, name in ((letters, "letters"), (digits, "digits")):
        if any(k == v for k, v in mapping.items()):
            raise ValueError(f"cipher {name} mapping has a fixed point")
        if sorted(mapping.values()) != sorted(mapping.keys()):
            raise ValueError(f"cipher {name} mapping is not a permutation")


def save_table(table, path=TABLE_PATH):
    validate_table(table)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(table, fh, sort_keys=True, indent=2)
        fh.write("\n")


def load_table(path=TABLE_PATH):
    with open(path, "r", encoding="utf-8") as fh:
        table = json.load(fh)
    validate_table(table)
    return table


def _invert(mapping):
    return {v: k for k, v in mapping.items()}


def encode(text, table):
    validate_table(table)
    letters, digits = table["letters"], table["digits"]
    out = []
    for ch in text:
        if ch.islower() and ch in letters:
            out.append(letters[ch])
        elif ch.isupper() and ch.lower() in letters:
            out.append(letters[ch.lower()].upper())
        elif ch in digits:
            out.append(digits[ch])
        else:
            out.append(ch)
    return "".join(out)


def decode(text, table):
    validate_table(table)
    letters = _invert(table["letters"])
    digits = _invert(table["digits"])
    out = []
    for ch in text:
        if ch.islower() and ch in letters:
            out.append(letters[ch])
        elif ch.isupper() and ch.lower() in letters:
            out.append(letters[ch.lower()].upper())
        elif ch in digits:
            out.append(digits[ch])
        else:
            out.append(ch)
    return "".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--emit-table", action="store_true",
                        help=f"write the seeded table to {TABLE_PATH}")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args(argv)
    if args.emit_table:
        table = build_table(args.seed)
        save_table(table)
        print(f"table written to {TABLE_PATH} (seed={args.seed})")
    if args.selftest:
        table = load_table()
        sample = "The barque Meridian, 900 tons of coal, sailed 4 March 1861."
        assert decode(encode(sample, table), table) == sample
        assert build_table(args.seed) == build_table(args.seed)
        print("selftest OK: round trip + determinism")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
